### PR TITLE
adding rust2pickle command

### PR DESCRIPTION
**Pull request by yijunyu**
Using serde-pickle to save the serialised Rust AST into pickle format for interfacing with Python

### CODE REVIEW

**Review by taiki-e — CHANGES_REQUESTED** [review]
Thanks for the PR! 

I would prefer not to add support for formats other than JSON as a public API for this crate at this time (additions of examples are very welcome).
Could you remove the changes on `syn-serde` crate and update the example to use `serde-pickle` directly?

**Comment by yijunyu** [comment]
Thanks for the suggestions. I have now removed the changes to the main library and placed the rust2pickle as an example project.

**Review by taiki-e — CHANGES_REQUESTED** [review]
Thanks, examples contained in this crate is not intended to be published as a crate at this time, so could you remove the last commit (e1def8a0a9274e60be214f82c578d82c82410c14)?

**Comment by yijunyu** [comment]
Yes, just managed to revert the last commit

**Review by taiki-e — APPROVED** [review]
Thanks! 

bors r+

**Pull request merged**
